# /etc/skel/.bashrc:

# This file is sourced by all *interactive* bash shells on startup.  This
# file *should generate no output* or it will break the scp and rcp commands.

#
# Aliases
#
eval `dircolors -b /etc/DIR_COLORS`
alias ls="ls"
alias ll="ls -al"
alias ll="ls -al"
alias ls-al="ls -al"
alias lcvs="cvs -d spock@hedwig:/cvs"
alias fbsdscvs="cvs -d mikeh@ncvs.freebsd.org:/home/ncvs"
alias fbsdpcvs="cvs -d mikeh@pcvs.freebsd.org:/home/pcvs"

alias svndiffls='svn diff \!* | grep ^Index | cut -d " " -f 2'
alias snv="svn"

alias rpmqvendor='rpm -qa --queryformat "%{NAME}-%{VENDOR}\n"'
alias run-enscript='enscript --media=Letter -GEc -fCourier7 -r -j -2 -v -C --lines-per-page=120 \!*'

alias makeit='make -s clean && make -s all && make -s install'

alias unrarit='unrar x -y \!*'
alias gr='grep -Irn \!$ .'

#
# Environment
#
export PATH=$HOME/bin:$PATH
export SVNROOT=svn+ssh://svn.bburg.evergrid.com/opt/svn/cdc
export NSVNROOT=svn+ssh://nagini.fesnel.com/var/svn/mikeh

export FLEX3_HOME=$HOME/tmp/flexsdk
export FLEX4_HOME=$HOME/tmp/flexsdk4

export FLEX_HOME=${FLEX4_HOME}

export FZLIB_HOME=$HOME/tmp/fzlib/FZlib

export MOZ_PLUGIN_PATH=$HOME/.firefox/plugins

#
# Editor
#
which xemacs &> /dev/null
if [ $? -eq 0 ]; then
	export EDITOR=xemacs
else
	which vim &> /dev/null
	if [ $? -eq 0 ]; then
	   export EDITOR=vim
	else
	   export EDITOR=vi
	fi
fi

export SVN_EDITOR=/home/mheffner/bin/svncitemp.sh
export SVN_REAL_EDITOR=$EDITOR


# Key bindings
export INPUTRC=$HOME/.inputrc

# History
export HISTSIZE=1024
HISTIGNORE='&'

# Coresize
ulimit -c 10240000

# Prompt
export PROMPT_DIRTRIM=3
function gitcurrbranch()
{
	local BRANCH=`git branch 2> /dev/null | awk '/^*/{print $2}'`
	if [ ! -z "$BRANCH" ]; then
	   printf "(\e[1;31m$BRANCH\e[m)"
	fi
}
function getwintitle()
{

    case $TERM in
	xterm*|rxvt|Eterm|eterm)
	    # Set icon title
	    printf "\[\033]1;\h:\`basename '\w'\`\007\]"
	    # Set window title
	    printf "\[\033]2;\h:\w\007\]"
	    ;;
	screen)
	    printf "\[\033_\h:\w\033\\"
	    ;;
	*)
	    ;;
    esac
}

export PS1="\h\`gitcurrbranch\`:\`tput bold\`\w\`tput sgr0\`$ `getwintitle`"

##uncomment the following to activate bash-completion:
#[ -f /etc/profile.d/bash-completion ] && source /etc/profile.d/bash-completion


# Display exit status of previous command on failure
#
function printexitvalue()
{
	local SAVE_EXIT=$?

	if [ $SAVE_EXIT -ne 0 ]; then
	   echo "Exit $SAVE_EXIT";
	fi

	return $SAVE_EXIT
}
export PROMPT_COMMAND=printexitvalue


#
# Source private bash file if it exists
#
if [ -e $HOME/.bash.priv ]; then
   . $HOME/.bash.priv
fi

# --Xemacs--
#
# -*- Local Variables:
# -*- mode:shell-script
# -*- End:
